### ISSUE TITLE
Help plugin developers automate releases

### ISSUE THREAD

**Issue by tomasbjerre** [jucies/releases#17]
As you know I now needed to create a new tag. It contained xyz-version instead of just version.
I also needed to browse to github repo page and mark tag as release.

I never used any Github release plugin so I cannot suggest anyone. But the API certainly has everything needed to automate releases of plugins to Jucies.

It can be solved by:
- Finding a github plugin that does this.
- Making, or contributing, to any existing github plugin.
- Creating a tiny script to add in developers .travis.yml that invokes the developers repo.

**Comment by bsideup** [comment]
Actually, one can go to Releases page, press "Create a new release" and that's it, the release is done. The idea of Jucies - avoid even building of plugins, you just create a new release on GitHub, everything else (building, publishing, etc) will be automatic.

I did some improvements to the generator, now, even if your tag is "my-plugin-1.2.3", it will strip plugin id from the start. Also, it will strip "v" prefix as well.

**Comment by tomasbjerre** [comment]
Ok good!
